import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NEXT LEARNING",
  description: "Generated by create next app",
};

export default function ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full font-semibold p-5 px-5 border-b">
          MEDIUM SITE
        </div>

        {children}
      </body>
    </html>
  );
}
